// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yW10TQnIzRFdK9K1vi_I3Y2sICA6oR0',
    appId: '1:606035065133:web:97d3c3fdf24969fc3cbba4',
    messagingSenderId: '606035065133',
    projectId: 'my-creavers-project-9ae09',
    authDomain: 'my-creavers-project-9ae09.firebaseapp.com',
    storageBucket: 'my-creavers-project-9ae09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7OLOLsmjPsuphbwnebgbhl6yAcVFYZY',
    appId: '1:606035065133:android:08d217ebd6ca1a743cbba4',
    messagingSenderId: '606035065133',
    projectId: 'my-creavers-project-9ae09',
    storageBucket: 'my-creavers-project-9ae09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD7HY_rzNu1N51TeA25pDCMUz_YJu-83A',
    appId: '1:606035065133:ios:6145851e71e115fa3cbba4',
    messagingSenderId: '606035065133',
    projectId: 'my-creavers-project-9ae09',
    storageBucket: 'my-creavers-project-9ae09.appspot.com',
    iosBundleId: 'com.example.creaversProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD7HY_rzNu1N51TeA25pDCMUz_YJu-83A',
    appId: '1:606035065133:ios:cfc5c47457ed50d33cbba4',
    messagingSenderId: '606035065133',
    projectId: 'my-creavers-project-9ae09',
    storageBucket: 'my-creavers-project-9ae09.appspot.com',
    iosBundleId: 'com.example.creaversProject.RunnerTests',
  );
}
